GLM_GTC_type_ptr: Memory layout access
GLM_GTC_type_ptr: Memory layout access
GTC Extensions (Stable)
Functions
template<typename T >
GLM_FUNC_QUALIFIER
detail::tmat2x2< T > make_mat2 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tmat2x2< T > make_mat2x2 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tmat2x3< T > make_mat2x3 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tmat2x4< T > make_mat2x4 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tmat3x3< T > make_mat3 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tmat3x2< T > make_mat3x2 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tmat3x3< T > make_mat3x3 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tmat3x4< T > make_mat3x4 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tmat4x4< T > make_mat4 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tmat4x2< T > make_mat4x2 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tmat4x3< T > make_mat4x3 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tmat4x4< T > make_mat4x4 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tquat< T > make_quat (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tvec2< T > make_vec2 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tvec3< T > make_vec3 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tvec4< T > make_vec4 (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tvec2< T > const &vec)
template<typename T >
GLM_FUNC_QUALIFIER T * value_ptr (detail::tvec2< T > &vec)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tvec3< T > const &vec)
template<typename T >
GLM_FUNC_QUALIFIER T * value_ptr (detail::tvec3< T > &vec)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tvec4< T > const &vec)
template<typename T >
GLM_FUNC_QUALIFIER T * value_ptr (detail::tvec4< T > &vec)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tmat2x2< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * value_ptr (detail::tmat2x2< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tmat3x3< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * value_ptr (detail::tmat3x3< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tmat4x4< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * value_ptr (detail::tmat4x4< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tmat2x3< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * value_ptr (detail::tmat2x3< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tmat3x2< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * value_ptr (detail::tmat3x2< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tmat2x4< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * value_ptr (detail::tmat2x4< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tmat4x2< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * value_ptr (detail::tmat4x2< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tmat3x4< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * value_ptr (detail::tmat3x4< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tmat4x3< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * value_ptr (detail::tquat< T > const &q)
template<typename T >
GLM_FUNC_QUALIFIER T * value_ptr (detail::tmat4x3< T > &mat)
Detailed Description
Handles the interaction between pointers and vector, matrix types.
This extension defines an overloaded function, glm::value_ptr, which takes any of the core template types. It returns a pointer to the memory layout of the object. Matrix types store their values in column-major order.
This is useful for uploading data to matrices or copying data to buffer objects.
Example:
 #include <glm/glm.hpp>
 #include <glm/gtc/type_ptr.hpp>
 glm::vec3 aVector(3);
 glm::mat4 someMatrix(1.0);
 glUniform3fv(uniformLoc, 1, glm::value_ptr(aVector));
 glUniformMatrix4fv(uniformMatrixLoc, 1, GL_FALSE, glm::value_ptr(someMatrix));
<glm/gtc/type_ptr.hpp> need to be included to use these functionalities.
Function Documentation
GLM_FUNC_QUALIFIER detail::tmat2x2<T> glm::make_mat2 (T const *const ptr)
Build a matrix from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 472 of file type_ptr.hpp.
References glm::make_mat2x2().
GLM_FUNC_QUALIFIER detail::tmat2x2<T> glm::make_mat2x2 (T const *const ptr)
Build a matrix from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 382 of file type_ptr.hpp.
References glm::value_ptr().
Referenced by glm::make_mat2().
GLM_FUNC_QUALIFIER detail::tmat2x3<T> glm::make_mat2x3 (T const *const ptr)
Build a matrix from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 392 of file type_ptr.hpp.
References glm::value_ptr().
GLM_FUNC_QUALIFIER detail::tmat2x4<T> glm::make_mat2x4 (T const *const ptr)
Build a matrix from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 402 of file type_ptr.hpp.
References glm::value_ptr().
GLM_FUNC_QUALIFIER detail::tmat3x3<T> glm::make_mat3 (T const *const ptr)
Build a matrix from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 480 of file type_ptr.hpp.
References glm::make_mat3x3().
GLM_FUNC_QUALIFIER detail::tmat3x2<T> glm::make_mat3x2 (T const *const ptr)
Build a matrix from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 412 of file type_ptr.hpp.
References glm::value_ptr().
GLM_FUNC_QUALIFIER detail::tmat3x3<T> glm::make_mat3x3 (T const *const ptr)
Build a matrix from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 422 of file type_ptr.hpp.
References glm::value_ptr().
Referenced by glm::make_mat3().
GLM_FUNC_QUALIFIER detail::tmat3x4<T> glm::make_mat3x4 (T const *const ptr)
Build a matrix from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 432 of file type_ptr.hpp.
References glm::value_ptr().
GLM_FUNC_QUALIFIER detail::tmat4x4<T> glm::make_mat4 (T const *const ptr)
Build a matrix from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 488 of file type_ptr.hpp.
References glm::make_mat4x4().
GLM_FUNC_QUALIFIER detail::tmat4x2<T> glm::make_mat4x2 (T const *const ptr)
Build a matrix from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 442 of file type_ptr.hpp.
References glm::value_ptr().
GLM_FUNC_QUALIFIER detail::tmat4x3<T> glm::make_mat4x3 (T const *const ptr)
Build a matrix from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 452 of file type_ptr.hpp.
References glm::value_ptr().
GLM_FUNC_QUALIFIER detail::tmat4x4<T> glm::make_mat4x4 (T const *const ptr)
Build a matrix from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 462 of file type_ptr.hpp.
References glm::value_ptr().
Referenced by glm::make_mat4().
GLM_FUNC_QUALIFIER detail::tquat<T> glm::make_quat (T const *const ptr)
Build a quaternion from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 496 of file type_ptr.hpp.
References glm::value_ptr().
GLM_FUNC_QUALIFIER detail::tvec2<T> glm::make_vec2 (T const *const ptr)
Build a vector from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 352 of file type_ptr.hpp.
References glm::value_ptr().
GLM_FUNC_QUALIFIER detail::tvec3<T> glm::make_vec3 (T const *const ptr)
Build a vector from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 362 of file type_ptr.hpp.
References glm::value_ptr().
GLM_FUNC_QUALIFIER detail::tvec4<T> glm::make_vec4 (T const *const ptr)
Build a vector from a pointer.
From GLM_GTC_type_ptr extension.
Definition at line 372 of file type_ptr.hpp.
References glm::value_ptr().
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tvec2< T > const & vec)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 81 of file type_ptr.hpp.
Referenced by glm::make_vec2(), glm::make_vec3(), glm::make_vec4(), glm::make_mat2x2(), glm::make_mat2x3(), glm::make_mat2x4(), glm::make_mat3x2(), glm::make_mat3x3(), glm::make_mat3x4(), glm::make_mat4x2(), glm::make_mat4x3(), glm::make_mat4x4(), and glm::make_quat().
GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tvec2< T > & vec)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 92 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tvec3< T > const & vec)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 103 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tvec3< T > & vec)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 114 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tvec4< T > const & vec)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 125 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tvec4< T > & vec)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 136 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat2x2< T > const & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 147 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat2x2< T > & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 158 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat3x3< T > const & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 169 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat3x3< T > & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 180 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat4x4< T > const & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 191 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat4x4< T > & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 202 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat2x3< T > const & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 213 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat2x3< T > & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 224 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat3x2< T > const & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 235 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat3x2< T > & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 246 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat2x4< T > const & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 257 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat2x4< T > & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 268 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat4x2< T > const & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 279 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat4x2< T > & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 290 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat3x4< T > const & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 301 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat3x4< T > & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 312 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat4x3< T > const & mat)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 323 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tquat< T > const & q)
Return the constant address to the data of the input parameter.
From GLM_GTC_type_ptr extension.
Definition at line 334 of file type_ptr.hpp.
GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat4x3< T > & mat)
Get the address of the matrix content.
From GLM_GTC_type_ptr extension.
Definition at line 344 of file type_ptr.hpp.